name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      
    - name: Format
      run:  'if [[ "$(gofmt -l ./ | tee /tmp/hubtty-playground-gofmt | wc -l)" -gt 0 ]]; then { echo "Run gofmt on these files:" | cat - /tmp/hubtty-playground-gofmt; return 1; }; fi'
    
    - name: Test
      run: go test -v ./...
